import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'My Next - Metadata',
    template: '%s | My Next'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex h-16 items-center justify-center bg-cadetblue text-white font-fantasy text-base font-black"
        >This is My Header</header>
        {children}
        <footer className="fixed bottom-0 w-full h-8 bg-cadetblue text-white flex items-center font-fantasy font-black">This is the footer</footer>
      </body>
    </html>
  );
}
